name: Reputation
version: 1.1
main: remagdbr.org.mine.reputation.Reputation
api-version: 1.20
commands:
  reputacao:
    description: Comandos de reputação
    usage: /reputacao [set|add|remove|chance] <jogador> <valor>